name: Sphinx documentation build

on: 
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PMIP_CBC_LIBRARY: "/home/runner/build/dist/lib/libCbc.so"
    steps:
      - uses: actions/checkout@v3
      - name: Compile CBC binary
        run : |
          sudo apt-get install gcc g++ gfortran libgfortran-9-dev liblapack-dev libamd2 libcholmod3 libmetis-dev libsuitesparse-dev libnauty2-dev git
          mkdir -p ~/build
          cd ~/build
          wget -nH https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
          bash coinbrew fetch Cbc@master --no-prompt --skip-update
          bash coinbrew build Cbc@stable/2.10 --no-prompt --tests=none
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with: 
          pre-build-command: "apt-get update -y --allow-releaseinfo-change && apt-get install -y git pandoc latexmk texlive-latex-recommended texlive-latex-extra dvipng texlive-fonts-recommended && pip install sphinx==7.1.2"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
